{
  "openapi": "3.0.0",
  "info": {
    "title": "Documentação da API de Anúncios de Imóveis",
    "description": "Nesta documentação você poderá consultar os endpoints da API e também testar todas as rotas disponíveis. Não se esqueça de se cadastrar e obter a autorização.",
    "contact": {
      "email": "evertondmcf@hotmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://anuncios-imoveis.onrender.com",
      "description": "Render Server"
    },
    {
      "url": "http://localhost:3000",
      "description": "Local Server"
    }

  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          },
          "background": {
            "type": "string"
          }
        }
      },
      "Imovel": {
        "type": "object",
        "properties": {
          "user": {
            "type": "string"
          },
          "cidade": {
            "type": "string"
          },
          "bairro": {
            "type": "string"
          },
          "rua": {
            "type": "string"
          },
          "numero": {
            "type": "number"
          },
          "tipoDeImovel": {
            "type": "string"
          },
          "tipoDeNegocio": {
            "type": "string"
          },
          "atualDisponibilidade": {
            "type": "string"
          },
          "telefoneContato": {
            "type": "string"
          },
          "imagemImovel": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date"
          }
        }
      }
    }
  },
  "paths": {
    "/user/": {
      "post": {
        "summary": "Criar novo usuário",
        "description": "Rota responsável por criar um novo usuário",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "Users": {
                  "value": {
                    "name": "Everton Dourado Mendes",
                    "username": "edm",
                    "email": "edm@gmail.com",
                    "password": "12345",
                    "avatar": "https://i.imgur.com/Ry1cb5M.png",
                    "background": "https://images.wallpapersden.com/image/download/triangle-8k-blue-pattern_bGZlbmiUmZqaraWkpJRmbmdlrWZlbWU.jpg"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Not Found"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "Buscar todos usuários",
        "description": "Rota responsável por buscar todos os usuários",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}/": {
      "get": {
        "summary": "Buscar usuário por id",
        "description": "Rota responsável por buscar usuário por id",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "User ID",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "patch": {
        "summary": "Editar usuário por id",
        "description": "Rota responsável por editar usuário por id",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "User ID",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "Users": {
                  "value": {
                    "name": "Thiago Lima"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/auth": {
      "post": {
        "summary": "Login no API Anúncios de Imóveis",
        "description": "Rota responsável por logar um usuário cadastrado",
        "tags": ["Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "User": {
                  "value": {
                    "email": "docencia.thiago@gmail.com",
                    "password": "12345"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/imovel/": {
      "post": {
        "summary": "Criar um novo anúncio de imovel",
        "description": "Rota responsável por criar um novo anúncio de imóvel",
        "tags": ["Imovel"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Imovel"
              },
              "examples": {
                "Imovel": {
                  "value": {
                    "cidade": "Guanambi",
                    "bairro": "Novo Horizonte",
                    "rua": "Rua Canadá",
                    "numero": "69",
                    "tipoDeImovel": "Casa",
                    "tipoDeNegocio": "Venda",
                    "atualDisponibilidade": "Indisponível",
                    "telefoneContato": "74988525555",
                    "imagemImovel": "https://pt.m.wikipedia.org/wiki/Ficheiro:Casa_Amarela.jpg"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Imovel"
                }
              }
            }
          }
        }
      }
    },
    "/imovel": {
      "get": {
        "summary": "Buscar todos os imoveis",
        "description": "Rota responsável por buscar todos os imóveis",
        "tags": ["Imovel"],
        "parameters": [
          {
            "in": "query",
            "name": "limit",
            "type": "string"
          },
          {
            "in": "query",
            "name": "offset",
            "type": "string"
          }
        ],
        "responses": {
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Imovel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/imovel/search": {
      "get": {
        "summary": "Buscar anúncios por cidade",
        "description": "Rota responsável por buscar os imóveis que correspondem à cidade enviada via query params",
        "tags": ["Imovel"],
        "parameters": [
          {
            "in": "query",
            "name": "cidade",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Imovel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/imovel/{id}/": {
      "get": {
        "summary": "Buscar anúncio por id",
        "description": "Rota responsável por buscar anúncios por id",
        "tags": ["Imovel"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "Imovel ID",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Imovel"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar um anúncio",
        "description": "Rota responsavel por deletar um anúncio",
        "tags": ["Imovel"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "Imovel ID",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/imovel/byUser": {
      "get": {
        "summary": "Buscar anúncios do usuário logado",
        "description": "Rota responsável por buscar anúncios do usuário logado",
        "tags": ["Imovel"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "400": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Imovel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/imovel/{id}": {
      "patch": {
        "summary": "Editar um anúncio",
        "description": "Rota responsável por editar um anúncio",
        "tags": ["Imovel"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "description": "Imovel ID",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Imovel"
              },
              "examples": {
                "Post": {
                  "value": {
                    "cidade": "Guanambi",
                    "bairro": "Novo Horizonte",
                    "rua": "Rua Canadá",
                    "numero": "69",
                    "tipoDeImovel": "Casa",
                    "tipoDeNegocio": "Venda",
                    "atualDisponibilidade": "Indisponível",
                    "telefoneContato": "74988525555",
                    "imagemImovel": "https://pt.m.wikipedia.org/wiki/Ficheiro:Casa_Amarela.jpg"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Imovel"
                }
              }
            }
          }
        }
      }
    }
}

}
